# Generated by Django 2.2.5 on 2022-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_customer_product_purchase_sales_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_qty',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_qty',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_number',
            field=models.CharField(max_length=256),
        ),
    ]
